- **DATA CLEANING**

In [1]:
import pandas as pd
df = pd.read_excel("/content/espn.xlsx")
df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6
1,HC Brook (ENG),2022-2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
59,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
60,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
61,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
62,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [2]:
df.head()

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6
1,HC Brook (ENG),2022-2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1

In [3]:
df.tail()

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
58,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
59,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
60,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
61,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
62,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  63 non-null     object
 1   Span    63 non-null     object
 2   Mat     63 non-null     int64
 3   Inns    63 non-null     int64
 4   NO      63 non-null     int64
 5   Runs    63 non-null     int64
 6   HS      63 non-null     object
 7   Ave     63 non-null     float64
 8   BF      61 non-null     object
 9   SR      63 non-null     float64
 10  100     63 non-null     int64
 11  50      63 non-null     int64
 12  0       63 non-null     int64
 13  4s      63 non-null     int64
 14  6s      63 non-null     int64
dtypes: float64(2), int64(9), object(4)
memory usage: 7.5+ KB

In [5]:
df = df.rename(columns={"Mat":"Matches_Played","Inns":"Innings_Played","NO":"Nots_Outs","HS":"Highest_Inns_Score","Ave":"Batting_Average","BF":"Balls_Faced","SR":"Strike_Rate"})
df

,Player,Span,Matches_Played,Innings_Played,Nots_Outs,Runs,Highest_Inns_Score,Batting_Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6
1,HC Brook (ENG),2022-2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
59,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
60,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
61,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
62,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [6]:
df.isnull().any()

Player                False
Span                  False
Matches_Played        False
Innings_Played        False
Nots_Outs             False
Runs                  False
Highest_Inns_Score    False
Batting_Average       False
Balls_Faced            True
Strike_Rate           False
100                   False
50                    False
0                     False
4s                    False
6s                    False
dtype: bool

In [7]:
df[df["Balls_Faced"].isna()]

,Player,Span,Matches_Played,Innings_Played,Nots_Outs,Runs,Highest_Inns_Score,Batting_Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s
9,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,NaN,0.0,15,19,6,258,2
15,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,NaN,0.0,15,14,1,107,11

In [8]:

df['Player'] = df['Player'].fillna(0)

In [9]:
df.isnull().any()

Player                False
Span                  False
Matches_Played        False
Innings_Played        False
Nots_Outs             False
Runs                  False
Highest_Inns_Score    False
Batting_Average       False
Balls_Faced            True
Strike_Rate           False
100                   False
50                    False
0                     False
4s                    False
6s                    False
dtype: bool

In [10]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
58    False
59    False
60    False
61    False
62    False
Length: 63, dtype: bool

In [11]:
df.drop_duplicates()

,Player,Span,Matches_Played,Innings_Played,Nots_Outs,Runs,Highest_Inns_Score,Batting_Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6
1,HC Brook (ENG),2022-2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
59,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
60,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
61,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
62,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [12]:
df["Initial_Year"] = df["Span"].str.split("-").str[0]
df["Retirement_Year"] = df["Span"].str.split("-").str[1]
df

,Player,Span,Matches_Played,Innings_Played,Nots_Outs,Runs,Highest_Inns_Score,Batting_Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Initial_Year,Retirement_Year
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6,1928,1948
1,HC Brook (ENG),2022-2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1,1930,1954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,1965,1981
59,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014
60,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,1924,1934
61,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,1930,1938
62,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,1928,1934

In [13]:
# The axis=1 parameter specifies that we are dropping columns (as opposed to rows, which would be indicated by axis=0)

In [14]:
df = df.drop(["Span"] , axis=1)
df

,Player,Matches_Played,Innings_Played,Nots_Outs,Runs,Highest_Inns_Score,Batting_Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Initial_Year,Retirement_Year
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6,1928,1948
1,HC Brook (ENG),12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023
2,AC Voges (AUS),20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016
3,RG Pollock (SA),23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970
4,GA Headley (WI),22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1,1930,1954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters (AUS),74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,1965,1981
59,GC Smith (ICC/SA),117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014
60,WH Ponsford (AUS),29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,1924,1934
61,SJ McCabe (AUS),39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,1930,1938
62,DR Jardine (ENG),22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,1928,1934

In [15]:
df["Highest_Inns_Score"] = df["Highest_Inns_Score"].str.split("*").str[0]
df["Balls_Faced"] = df["Balls_Faced"].str.split("+").str[0]

df

,Player,Matches_Played,Innings_Played,Nots_Outs,Runs,Highest_Inns_Score,Batting_Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Initial_Year,Retirement_Year
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,1928,1948
1,HC Brook (ENG),12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023
2,AC Voges (AUS),20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016
3,RG Pollock (SA),23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,1963,1970
4,GA Headley (WI),22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,1930,1954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters (AUS),74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,1965,1981
59,GC Smith (ICC/SA),117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014
60,WH Ponsford (AUS),29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,1924,1934
61,SJ McCabe (AUS),39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,1930,1938
62,DR Jardine (ENG),22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,1928,1934

In [16]:
df["Country"] = df["Player"].str.split("(").str[1]
# df

In [17]:
df["Country"] = df["Country"].str.split(")").str[0]
# df

In [18]:
df["Player"] = df["Player"].str.split("(").str[0].str.strip()
df

,Player,Matches_Played,Innings_Played,Nots_Outs,Runs,Highest_Inns_Score,Batting_Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Initial_Year,Retirement_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,1928,1948,AUS
1,HC Brook,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023,ENG
2,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
3,RG Pollock,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,1963,1970,SA
4,GA Headley,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,1930,1954,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,1965,1981,AUS
59,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA
60,WH Ponsford,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,1924,1934,AUS
61,SJ McCabe,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,1930,1938,AUS
62,DR Jardine,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,1928,1934,ENG

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Player              63 non-null     object
 1   Matches_Played      63 non-null     int64
 2   Innings_Played      63 non-null     int64
 3   Nots_Outs           63 non-null     int64
 4   Runs                63 non-null     int64
 5   Highest_Inns_Score  63 non-null     object
 6   Batting_Average     63 non-null     float64
 7   Balls_Faced         61 non-null     object
 8   Strike_Rate         63 non-null     float64
 9   100                 63 non-null     int64
 10  50                  63 non-null     int64
 11  0                   63 non-null     int64
 12  4s                  63 non-null     int64
 13  6s                  63 non-null     int64
 14  Initial_Year        63 non-null     object
 15  Retirement_Year     63 non-null     object
 16  Country             63 non-null     object
dtypes: float64(2), int64(9), object(6)
memory usage: 8.5+ KB

In [20]:
df.isnull().any()

Player                False
Matches_Played        False
Innings_Played        False
Nots_Outs             False
Runs                  False
Highest_Inns_Score    False
Batting_Average       False
Balls_Faced            True
Strike_Rate           False
100                   False
50                    False
0                     False
4s                    False
6s                    False
Initial_Year          False
Retirement_Year       False
Country               False
dtype: bool

In [21]:
df["Balls_Faced"] = df["Balls_Faced"].fillna(0)

In [22]:
df.isnull().any()

Player                False
Matches_Played        False
Innings_Played        False
Nots_Outs             False
Runs                  False
Highest_Inns_Score    False
Batting_Average       False
Balls_Faced           False
Strike_Rate           False
100                   False
50                    False
0                     False
4s                    False
6s                    False
Initial_Year          False
Retirement_Year       False
Country               False
dtype: bool

In [23]:
df = df.astype({"Highest_Inns_Score":int,"Balls_Faced":int,"Initial_Year":int,"Retirement_Year":int})

ValueError: invalid literal for int() with base 10: '-': Error while type casting for column 'Balls_Faced'

In [24]:
df[df["Balls_Faced"]=="-"]

,Player,Matches_Played,Innings_Played,Nots_Outs,Runs,Highest_Inns_Score,Batting_Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Initial_Year,Retirement_Year,Country
55,Hon.FS Jackson,20,33,4,1415,144,48.79,-,0.0,5,6,3,51,0,1893,1905,ENG

In [25]:
df[df["Player"]=="Hon.FS Jackson"] = df[df["Balls_Faced"]=="-"].replace("-",0)

In [26]:
df = df.astype({"Highest_Inns_Score":int,"Balls_Faced":int,"Initial_Year":int,"Retirement_Year":int})

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Player              63 non-null     object
 1   Matches_Played      63 non-null     int64
 2   Innings_Played      63 non-null     int64
 3   Nots_Outs           63 non-null     int64
 4   Runs                63 non-null     int64
 5   Highest_Inns_Score  63 non-null     int64
 6   Batting_Average     63 non-null     float64
 7   Balls_Faced         63 non-null     int64
 8   Strike_Rate         63 non-null     float64
 9   100                 63 non-null     int64
 10  50                  63 non-null     int64
 11  0                   63 non-null     int64
 12  4s                  63 non-null     int64
 13  6s                  63 non-null     int64
 14  Initial_Year        63 non-null     int64
 15  Retirement_Year     63 non-null     int64
 16  Country             63 non-null     object
dtypes: float64(2), int64(13), object(2)
memory usage: 8.5+ KB

In [28]:
df["Career_Span"] = df["Retirement_Year"] - df["Initial_Year"]
df

,Player,Matches_Played,Innings_Played,Nots_Outs,Runs,Highest_Inns_Score,Batting_Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Initial_Year,Retirement_Year,Country,Career_Span
0,DG Bradman,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,1928,1948,AUS,20
1,HC Brook,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023,ENG,1
2,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS,1
3,RG Pollock,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,1963,1970,SA,7
4,GA Headley,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,1930,1954,WI,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,1965,1981,AUS,16
59,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA,12
60,WH Ponsford,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,1924,1934,AUS,10
61,SJ McCabe,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,1930,1938,AUS,8
62,DR Jardine,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,1928,1934,ENG,6

In [29]:
df.describe()

,Matches_Played,Innings_Played,Nots_Outs,Runs,Highest_Inns_Score,Batting_Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Initial_Year,Retirement_Year,Career_Span
count,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000
mean,79.349206,134.428571,14.000000,6359.285714,249.079365,53.685238,9950.952381,47.459683,19.126984,28.317460,7.761905,646.000000,27.031746,1970.380952,1983.492063,13.111111
std,50.997204,86.896437,11.123935,4034.488549,61.008540,7.188137,9131.917997,15.485213,12.429793,18.683118,5.537888,523.353116,27.090629,34.921769,34.100361,5.579661
min,12.000000,20.000000,1.000000,990.000000,122.000000,48.000000,0.000000,0.000000,1.000000,3.000000,1.000000,37.000000,0.000000,1893.000000,1905.000000,1.000000
25%,26.000000,44.500000,5.000000,2223.000000,206.000000,49.520000,1811.000000,42.465000,7.000000,10.500000,3.000000,144.500000,5.000000,1936.000000,1954.500000,9.500000
50%,79.000000,132.000000,12.000000,6235.000000,243.000000,51.620000,7809.000000,49.160000,19.000000,28.000000,7.000000,543.000000,20.000000,1976.000000,1993.000000,14.000000
75%,117.500000,196.500000,19.000000,8840.000000,277.500000,56.675000,16000.500000,55.035000,29.000000,42.000000,12.000000,1056.000000,41.500000,2000.000000,2013.500000,17.000000
max,200.000000,329.000000,49.000000,15921.000000,400.000000,99.940000,31258.000000,91.760000,51.000000,68.000000,22.000000,2058.000000,97.000000,2022.000000,2024.000000,24.000000